// automatic

a = 3;
b = 7;
c = a + b;
console.log(c);
var x = 3;
var y = 7;
var z = x + y;
console.log(z);

let e = 3;
let f = 7;
let g = e + f;
console.log(g);
const q = 3;
const p = 7;
const r = p + q;
console.log(r);
var x = 7;
var y = 3;
var z = x + y;
console.log(z);
let d = 7;
let t = 3;
let k = d + t;
console.log(k);
let value1 = true;
console.log(typeof value1);
let value2 = "Eden";
console.log(typeof value2);
let value3 = "10";
let value4 = Number(value3);
console.log(typeof value4);
let value5 = 10;
let value6 = String(value5);
console.log(typeof value6);
let remainder = 10 % 3;
console.log(remainder);
let addition = 5 + 5;
console.log(addition);
let division = 20 / 2;
console.log(division);
let div = 20 / 2;
console.log(div);
